# Generated by Django 4.0 on 2022-01-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
