# Generated by Django 4.0 on 2022-01-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0003_alter_item_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', to_field='username'),
        ),
    ]
