# Generated by Django 4.0 on 2022-01-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_item_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Category',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
