# Generated by Django 4.0 on 2022-01-11 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0005_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField()),
                ('itemName', models.CharField(max_length=255)),
                ('itemDesc', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('customerName', models.CharField(default='null', max_length=255)),
                ('phone', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', to_field='username')),
            ],
        ),
    ]
