# Generated by Django 4.0 on 2022-01-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0008_alter_company_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', to_field='username'),
        ),
    ]
