# Generated by Django 4.0 on 2022-01-13 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_company_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 13)),
        ),
    ]
