# Generated by Django 4.0 on 2022-01-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_fuel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='date',
            field=models.DateField(),
        ),
    ]
