# Generated by Django 4.0 on 2022-01-13 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0012_alter_fuel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 13)),
        ),
        migrations.CreateModel(
            name='tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelname', models.CharField(max_length=255)),
                ('totalquantity', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', to_field='username')),
            ],
        ),
    ]
