# Generated by Django 4.0 on 2022-01-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0013_alter_fuel_date_tank'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelname', models.CharField(max_length=255)),
                ('customername', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('platenumber', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', to_field='username')),
            ],
        ),
    ]
