# Generated by Django 4.0 on 2022-01-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_itemdesc_record_customername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='customername',
            new_name='cname',
        ),
    ]
