# Generated by Django 4.0 on 2022-01-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_customername_record_cname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customername',
        ),
    ]
