# Generated by Django 4.0 on 2022-01-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_customer_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customername',
            field=models.CharField(default='', max_length=255),
        ),
    ]
