# Generated by Django 4.0 on 2022-01-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_customer_customername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='fuelname',
        ),
    ]
