# Generated by Django 4.0 on 2022-01-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_record_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='itemId',
        ),
    ]
